[package]
name = "imbe"
version = "1.0.0"
authors = ["Mick Koch <mick@kochm.co>"]

[dependencies]

arrayvec = "^0.3.12"
collect_slice = "^1.0.0"
crossbeam = "^0.2.10"
iq_osc = {version = "^3.0.0", git = "https://github.com/kchmck/iq_osc.rs"}
num = "^0.1.34"
rand = "^0.3"
slice_mip = "1.0.0"
