[package]
name = "imbe"
version = "1.0.0"
authors = ["Mick Koch <mick@kochm.co>"]

[dependencies]
arrayvec = "0.3.12"
num = "0.1.29"
collect_slice = "1.0.0"
rand = "0.3"
quad_osc = {version = "1.0.0", path = "../quad_osc"}
thread-scoped = "1.0.1"
